name: Test Deploy Pipeline

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "✅ GitHub Actions is working correctly and triggered on

